# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: holiday01/devops_test
  tag: latest

app:
    name: myapp


deployment:
    name: myapp


nameOverride: "my-app"
fullnameOverride: "my-app"




ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - myapp.test.com
  tls: []



persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"
  accessMode: ReadWriteOnce
  mountPath: /data-mount




service:
  type: ClusterIP
  port: 5000

blackboxExporter:
  enabled: true

vmAgent:
  enabled: true


prometheus:
  additionalScrapeConfigs:
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module:
          - "http_2xx"
      static_configs:
        - targets:
            - http://myapp.test.com



